### ISSUE TITLE
DFlipFlop

### ISSUE THREAD

**Issue by vntyadav1228** [BinPy/BinPy#105]
in sequential.py Dflipflop in not correctly implemented , Flipflops are edge triggered . DFlipFlop in sequential.py is level triggered

**Comment by salilkapur** [comment]
Yes, feel free implement this feature.

**Comment by ghost** [comment]
@debugger22 - Implemented in merged PR #126 . Can now be closed !

**Comment by debugger22** [comment]
Thanks!
