### ISSUE TITLE
On outputs

### ISSUE THREAD

**Issue by petermlm** [BinPy/BinPy#140]
Wanting to know the output of a gate or connector or other digital element is quite common in this library. I propose the usage of the __repr__() function in the respective classes to simplify the following code:

```
g1 = AND(True, True)
print g1.output()
```

To this:

```
g1 = AND(True, True)
print g1
```

~~Also, how about having a function for the gates classes that would display the value of every input. Like the following:~~

```
>>> g1 = AND(True, False, True)
>>> print g1.inputs()
[1, 0, 1]
```

~~I believe more things can be done to have more and better outputs then just the simple output function. What do you guys things? I can implement these things if you like.~~

Edit: Ops, there is already a getInputStates() function that does just that.

It might also be interesting to have some backtrack feature that extends what getInputStates displays(). Suppose the following code:

```
gx1 = AND(False, False)
gx2 = AND(True, True)

c1 = Connector()
c2 = Connector()

gx1.setOutput(c1)
gx2.setOutput(c2)

gy = AND(c1, c2)
print gy.getInputStates()
print gy.backtrack()
```

The output of getInputStates() is just:

```
[0, 1]
```

The output of backtrack() would be:

```
[[0, 0], [1, 1]]
```

So the two sub lists are in fact the result of getInputStates() of the two other gates.

This feature could even be given a parameter to backtrack only to a certain time or until a loop has been reached. Not sure if this would be useful to the user (programmer as user of library). But it might came in handy for some operations in big circuits.

@jayrambhia , what would you say about this?

**Comment by jayrambhia** [comment]
Yeah. This is a great idea. I had tried this previously, but due to some class descriptor issues, I couldn't finish it and the branch went dead. You should definitely start working on this. Seems like a good idea.
