### ISSUE TITLE
Having specific input and output classes.

### ISSUE THREAD

**Issue by petermlm** [BinPy/BinPy#141]
In some circuit simulator there is a specific digital element for inputs and outputs. An input is just an element that can be set to zero or one and it can be connected to any other other digital element. An output is like an input but it receives it's value from one connection.

Currently BinPy doesn't really have and input and output digital element. In fact, if we want to initialize a Gate or connector we can just do the following:

```
c1 = Connector(True)
c2 = Connector(False)
g = AND(c1, c2)
```

So, by hardcoding the initial value we get the notion of initial input. But having specific input and output classes may be useful for the following reasons:
- First reason - Code organization

Suppose you have a few inputs and a big circuit to work with and that circuit is not closed, that is, it has some initial values that are hardcoded like in the example above.

By having an input class you can define the value very much like in the example above, except this time you get an input instead of a connection:

```
i1 = Input(True)
i2 = Input(False)
g = AND(i1, i2)
```
- Second reason - Setting the value makes more sense

It just doesn't seem to make sense to explicitly set the value of a connector, in fact, that shouldn't even be allowed. A connector is just a wire that goes from one digital element to another, you don't look at a connector and say, "Now your value is 1". (Or at least, I don't think we do that).

By having this notion of input this situation ceases to exist.
- Third reason - GUI simulator

If I were to work on the GUI project for GSoC, I would implement this notion of inputs and outputs. When we look at the graphical representation of a circuit in a simulation program we want to be able to tell where is a given input (in a non closed circuit) and change it to fit our needs and see the simulation working. So we have an element that we can toggle and really represents this.

We also want to see an output to know what the value of the circuit is. So we have another digital element that takes in one connection and displays the value.

To do this it is not really important to have a representation of an input and output at the BinPy library level, but it would still be nice to have it.

If you like the idea I can implemented ASAP.

**Comment by rajat974** [comment]
There will be a bit confusion with the implementation, of having two different types of connections, one input and other one output. Second, The bit that is input in one device maybe output from another device then it requires separate handling for GUI implementation, which is not required in case of using Connector.

**Comment by petermlm** [comment]
Well, I don't really think there will be much confusion because they aren't really types of connections, just two different new digital elements that work pretty much like Gates do. The main difference is that this two new digital elements provide the direct abstraction of input and output for a given circuit whereas the simple connectors do not.

About the GUI simulator. Well, I would think of a sub circuit as an element which you can drag and has inputs and output just like Gates and ICs have. Particularly, the inputs, outputs and behavior of these elements would depend on their design, which would be implemented in the simulator. So if we were to design a simple circuit with, say, three inputs and two outputs, then our new digital element to use would have that same number of inputs and outputs.

The point being, that this way we are explicitly specifying the i/o of a circuit using digital elements. Just using loose connectors would achieve this, however the look of the circuit, in the GUI, would not be as appealing.

So, concluding, maybe having Input and Output elements in the Library is not that important, but I strongly recommend their implementation in the GUI simulator, that implementation being like the one in the Logisim simulator.

**Comment by rajat974** [comment]
As far as you want them to be distinguished, we have the difference in the Connector class , where we store its nature in the dictionary. So to render that in GUI we can get its nature and then put that in gui

**Comment by petermlm** [comment]
Yes I guess you could do that. So there is no need the explicitly have an Input and Output class.

Very well I'll close this issue.

Thanks for the feedback @rajat974.
