### ISSUE TITLE
Connectors contructor

### ISSUE THREAD

**Issue by petermlm** [BinPy/BinPy#144]
We have the following constructor for the connector class:

```
class Connector:

    def __init__(self, state=None):
        self.connections = {"output": [], "input": []}
            # To store the all the taps onto this connection
        self.state = state  # To store the state of the connection
        self.oldstate = None
```

It takes a state as argument. Would it make sense to have the constructor take a gate as argument and run the Tap() method to add said gate to the connections dictionary?

I say this because it might be convenient for someone to write the following code:

```
g = AND(...)
c = Connector(g)
```

instead of:

```
g = AND(...)
c = Connector()
g.setOutput(c)
```

Even if it is not desirable to have such a feature maybe have an exception in this constructor that is raised if the state is not an int or bool.

If someone gives me feedback on this preferring either of the scenarios I'll implement it ASAP!

**Comment by mohitgujarathi14** [comment]
To implement , 

``` python
g = AND(...)   
c = Connector(g)   
```

or this,

``` python
a = Connector(...)   
c = Connector(a)
```

we can add the following to _**init**_ of class **Connector** .

``` python
if isinstance(state,Connector):
    self.state = state.state 
elif isinstance(state,GATES):
    self.state = state.output()   
```

**Comment by petermlm** [comment]
@mohitgujarathi14, I actually meant something more like this:

```
if isinstance(state, GATES):
    self.tap(state, "input")
    state.setOutput(self)
```

So, state would be a gate (the name state wouldn't really make sense like this). The connection would have an input from the gate in the argument and the gate would have this connector as an output.

**Comment by mohitgujarathi14** [comment]
For:

```
g = AND(...)
c = Connector(g)
```

Your code will tap 'gate' into both input and output of c.connections.How will you provide an input of the gate as a argument(state) when you propose 'state' to be instance of gate.
And isnt 'input from the gate' infact the 'output' of that gate?

**Comment by petermlm** [comment]
Yes that it, my mistake.

Anyway, there is a problem with this. Because the **connetor.py** file gets imported from the **gates.py** file, the **gates.py** file can't be imported from the **connector.py** file. So the proposition I gave can't be made.

However, we should still validade the state variable to check if it is an **bool**, **int**, or if it is nothing, **NoneType**. Problems might be raised if the state variable is some object. Even if they don't it is just not correct to allow such a thing. For that the constructor would just be:

```
    def __init__(self, state=None):
        self.connections = {"output": [], "input": []}
            # To store the all the taps onto this connection

        if type(state) not in [bool, int] and state != None:
            raise Exception("ERROR:Bad state type")

        self.state = state  # To store the state of the connection
        self.oldstate = None
```

**Comment by mohitgujarathi14** [comment]
@petermlm The case when the argument(state) is either a gate/conector shouldnt be treated as a issue though. When the circuits would get bigger and complex,

``` python
if isinstance(state,Connector):
    self.state = state.state 
```

 we would probably need this to create nodes( eg. two connectors merging into a third),
whose importance cant be seen as much in Digital circuits as in Analog circuits .

``` python
elif isinstance(state,GATES):
    self.state = state.output()
```

and this when perhaps the connector is simply taking its value from a gate.
