### ISSUE TITLE
PEP8 Compatibility

### ISSUE THREAD

**Issue by rajat974** [BinPy/BinPy#164]
Before sending PR, we should run the following steps:

To make the code pep8 comapatible:

```
sudo pip install --upgrade autopep8
```

For autopep8ing a file 

```
autopep8 --in-place --aggressive --aggressive <filename>
```

For autopep8ing a folder 

```
autopep8 --in-place --recursive --aggressive --aggressive <foldername>
```

After that, to check the pep8 errors

```
pep8 --ignore=E501 ./
```

**Comment by rajat974** [comment]
@jayrambhia Can we do something instead of adding test, where developer run these commands before pushing ?

**Comment by jayrambhia** [comment]
Yeah. There are tools available that convert to PEP8.

**Comment by rajat974** [comment]
Yeah one of the tool, I had mentioned in the description above, which automatically converts into pep8.

**Comment by rajat974** [comment]
@debugger22 needs to be closed.

**Comment by debugger22** [comment]
Thanks! It was fixed in https://github.com/BinPy/BinPy/pull/181.
