### ISSUE TITLE
Detecting cycles in the Tree functionality

### ISSUE THREAD

**Issue by petermlm** [BinPy/BinPy#174]
So I've noticed that the implementation of the Tree class has one or two details that are not quite right, but they are minor and I can correct them. One of the has to do with how the depth parameter is off by one, meaning that depth 0 should only be something like:

```
|- AND Gate; Output: 0; Inputs: [0, 0];
```

But instead display something like:

```
|- AND Gate; Output: 0; Inputs: [0, 0];
   |- AND Gate; Output: 0; Inputs: [True, 0];
   |- AND Gate; Output: 0; Inputs: [True, False];
```

It a minor problem. I can fix that. I also noticed that some of the tuples were not being well constructed. So I'll fix that to. What I wanted to talk about was that we can add an argument to the ~~printTuple() method~~ Tree constructor that, when true, doesn't display cycles. Take the following example. The gates marked with [1] are the same:

```
|- [1] AND Gate; Output: 0; Inputs: [0, 0];   # <--------------
   |- AND Gate; Output: 0; Inputs: [True, 0];
      |- True
      |- Connector; State: 0
         |- [1] AND Gate; Output: 0; Inputs: [0, 0];   # <--------------
            |- AND Gate; Output: 0; Inputs: [True, 0];
               |- True
               |- Connector; State: 0
                  |- [1] AND Gate; Output: 0; Inputs: [0, 0];   # <--------------
                     |- AND Gate; Output: 0; Inputs: [True, 0];
                        |- True
                        |- Connector; State: 0
                           |- [1] AND Gate; Output: 0; Inputs: [0, 0];   # <--------------
                     |- AND Gate; Output: 0; Inputs: [True, False];
                        |- True
                        |- False
            |- AND Gate; Output: 0; Inputs: [True, False];
               |- True
               |- False
   |- AND Gate; Output: 0; Inputs: [True, False];
      |- True
      |- False
```

If the argument is true, the extra pointless lines won't show up!

I can implement this. Thoughts?

**Comment by petermlm** [comment]
Oh, and the code that generates the example:

```
c = Connector(True)

g1 = AND(True, c)
g2 = AND(True, False)
g3 = AND(g1, g2)
g3.setOutput(c)
```

**Comment by rajat974** [comment]
depth 0 is giving the right result for me . Can you put the actual code which is giving error?

**Comment by petermlm** [comment]
@rajat974 , strange. That was the actual code that was giving me the incorrect result. I'm going to to check if there was any update after I detected the bug.

**Comment by rajat974** [comment]
No, i am talking about the script which is giving you the wrong result for depth 0

**Comment by petermlm** [comment]
I believe it was the one which you made based on the initial code I had:

https://github.com/BinPy/BinPy/commit/f968e75820e5974bf573fe157986b77000832b0e#diff-149e1c8dec050c4a7349d0ba8a6d26bc

It's strange. I must be doing something wrong. But don't worry, I'll summit a pull request later today to implement the cycles feature.

**Comment by rajat974** [comment]
@debugger22 needs to be closed.

**Comment by debugger22** [comment]
Thanks! Fixed in https://github.com/BinPy/BinPy/pull/175.
