### ISSUE TITLE
Tests for code quality is required

### ISSUE THREAD

**Issue by debugger22** [BinPy/BinPy#179]
We should have code quality tests in Travis builds to check bad formatting, whitespaces, newline problem, etc.

**Comment by rajat974** [comment]
I had proposed pep8 testing #164.  Can we add that ? Its very easy to `autopep8` with a single command and it will solve our problems.

**Comment by rajat974** [comment]
See #181

**Comment by debugger22** [comment]
Fixed with https://github.com/BinPy/BinPy/pull/181
