### ISSUE TITLE
Tests fail occasionally

### ISSUE THREAD

**Issue by debugger22** [BinPy/BinPy#192]
Similar to https://github.com/BinPy/BinPy/issues/188 even this test failed recently. Passed after a restart.

```
FAIL: BinPy.tests.counters_tests.test_NBitDownCounter
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.6/lib/python2.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/BinPy/BinPy/BinPy/tests/counters_tests.py", line 47, in test_NBitDownCounter
    0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1]
AssertionError
```

Here the clocks are also being killed.

**Comment by ghost** [comment]
Could it be because of a high clock frequency ? There could have been a loss of synchronization in thread ? ( The thread which runs clock could have been queued for too long a period ) or some thing like that ?

**Comment by rajat974** [comment]
@rvraghav93 one reason could be that we use different clock frequency and threads synchronisation do not happen. probably we can fix to a single value or a single clock for whole of the tests.
