### ISSUE TITLE
Implement Carry-lookahead adder

### ISSUE THREAD

**Issue by mishravikas** [BinPy/BinPy#210]
A carry-lookahead adder improves the speed by reducing the amount of time required for calculating carry bits, of course it doesn't make much difference for smaller inputs but  it can make a difference in case of large inputs.
Here's more about it https://en.wikipedia.org/wiki/Carry-lookahead_adder

**Comment by debugger22** [comment]
:+1: from me.

**Comment by axiom24** [comment]
yeah go ahead and implement it

**Comment by salilkapur** [comment]
See if you can also implement a Ripple Adder.
