### ISSUE TITLE
A way to add names to connector needed.

### ISSUE THREAD

**Issue by ghost** [BinPy/BinPy#211]
1. We could get name from user - Users might duplicate names.
2. We could use the `globals()` to return the names of variables as a neat `dict`.

My idea is like [this](http://nbviewer.ipython.org/gist/rvraghav93/11229210)

There is one problem however. I am not able to call the `setName` function in `__init__` since only `self` is initialized at that time. When control is inside `__init__` the instance [ c in the above example ] does not get into `globals()` itself. It is added to `globals()` only when `__init__` returns ...

How is this? Any suggestions ?

Motivation: It would be easier to debug connections.

**Comment by debugger22** [comment]
There's a 404.

**Comment by ghost** [comment]
Now ?

**Comment by coder006** [comment]
@rvraghav93 can u give an example as to what u are exactly trying to do? As in your code.

**Comment by ghost** [comment]
@coder006 At the end of the ipython notebook I have printed out the result. Without this `name` the output would be: `Connector; State: None`

That is it auto generates an identification name for the connector instance.

And in general the basic idea is that if I am debugging a connection to say a multi input gate. This could be useful to differentiate among the different input connectors.

**Comment by debugger22** [comment]
I think you are right here. This is a good thing to have.

**Comment by ghost** [comment]
Ok then :)
