### ISSUE TITLE
MIGATES class in gates.py

### ISSUE THREAD

**Issue by akshayah3** [BinPy/BinPy#225]
Is that class really required as the `setinputs` method of the `GATE` class does the same?

**Comment by akshayah3** [comment]
[Here](https://github.com/BinPy/BinPy/blob/develop/BinPy/Gates/gates.py) is the link.

**Comment by debugger22** [comment]
You are correct. It's not required now.

**Comment by akshayah3** [comment]
Should i send a PR?

**Comment by debugger22** [comment]
Sure! If you want.
