### ISSUE TITLE
ERROR: Draw Failed - 'module' object has no attribute 'symbols'

### ISSUE THREAD

**Issue by Rapternmn** [BinPy/BinPy#266]
After changing the base.py file,i tried to run the program again and got this error
Please help

**Comment by debugger22** [comment]
> After changing the base.py file

What change?

**Comment by Rapternmn** [comment]
symbols.symbols to symbols..as mentioned by raghav sir in previous issue of draw_IC() attribute error

https://github.com/BinPy/BinPy/blob/develop/BinPy/ic/base.py#L49

line 49

**Comment by debugger22** [comment]
https://github.com/BinPy/BinPy/issues/265 has already been fixed by @rvraghav93 .

**Comment by Rapternmn** [comment]
okok
