### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by Mushirahmed** [BinPy/BinPy#285]
Dear BinPy Support Team,
I am installing the BinPy library using git clone method.
Following is the issue regarding to installation.
Cloning into 'BinPy'...
error: The requested URL returned error: 407 while accessing http://github.com/BinPy/BinPy.git/info/refs
fatal: HTTP request failed

**Comment by debugger22** [comment]
I think this is GitHub who is stopping you. https://github.com/blog/809-git-dumb-http-transport-to-be-turned-off-in-90-days

**Comment by Mushirahmed** [comment]
I am using latest version i.e 1.7.9.5 of git
Still it is not giving same error

**Comment by debugger22** [comment]
Oh! I would suggest you to download the package from [here](https://github.com/BinPy/BinPy/archive/v0.3.1.tar.gz) and install it manually. Let me know if you face any problem.

**Comment by salilkapur** [comment]
For time being, I suggest you to download the zip of the master branch.

**Comment by Mushirahmed** [comment]
Dear Sudhanshu and Salil,
Thanks..
BinPy now successfully installed.
