### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by mssurajkaiga** [BinPy/BinPy#39]
Currently there is no documentation, not even auto generated basic documentation explaining the structure. I recommend we use Sphinx for creating and managing the docs. http://sphinx-doc.org/

**Comment by debugger22** [comment]
Here's the link to documentation generated using Sphinx http://packages.python.org/BinPy/

**Comment by mssurajkaiga** [comment]
It would be better if it's added in the readme.. I will modify it and send a pull request.
