### ISSUE TITLE
Power source

### ISSUE THREAD

**Issue by debugger22** [BinPy/BinPy#42]
One of the important component we are missing is a power source. We didn't feel the necessity of it while creating gates and other stuffs but components like ICs and other devices will require power source for validity. It should also be connected via the same connector class. Any ideas, how to sort it out?

**Comment by debugger22** [comment]
That is why writing code for this IC was difficult https://github.com/BinPy/BinPy/blob/develop/BinPy/ic/series_7400_1.py#L3-L35

**Comment by abhinavgupta** [comment]
This can get ugly, I had thought of it, but this will be mixing analog structures with digital.

**Comment by debugger22** [comment]
Then Force constant/clock will be an option, right?

**Comment by ssr09** [comment]
Addressed in PR #101 Added Ground too.

**Comment by debugger22** [comment]
Added in https://github.com/BinPy/BinPy/pull/101
