### ISSUE TITLE
Having Gates with 3 & 4 inputs

### ISSUE THREAD

**Issue by rajat974** [BinPy/BinPy#48]
Till now BinPy only has gates with two inputs, we can include it with 3 and 4 inputs. It is of much use in digital processing and as well as making other type of standard circuits.

I am working on this. Waiting for the suggestions.

**Comment by salilkapur** [comment]
@rajat974 BinPy has support for multiple input gates too. We are trying to refactor the entire logic gates code in the library. It will take a day or two more. The logic gates will work for n number of inputs.

**Comment by rajat974** [comment]
@salil93  will that include all tests also for different modules separately ?

**Comment by salilkapur** [comment]
We will try to cover as many as we can. But you can always help us in making tests more extensive.

**Comment by rajat974** [comment]
Can you just put up some prototype because since you said entire gate design is going to change, that means other stuff can't be introduce until that part is done.
