### ISSUE TITLE
Add Sequential Circuits

### ISSUE THREAD

**Issue by salilkapur** [BinPy/BinPy#62]
We only have SR Latch and D Flip Flop implemented right now.

The following Circuits need to be implemented.

JK Flip Flop
T Flip Flop
Counters

**Comment by anantk17** [comment]
Shouldn't the D Flip Flop implementation have just one input, the current implementation uses 2.

**Comment by salilkapur** [comment]
One input and the other one is enable.

**Comment by ghost** [comment]
@debugger22 - Implemented in merged PR #126 . Can now be closed !
